# Training & Validation (FaceShifter)
dataset:
  train_dataset: 'triplet_lia_0_600000'  # 'image_512_quality', 'triplet_0_100000', 'triplet_lia_0_100000'
  val_dataset: 'image_512_quality'
  triplet_ratio: 100
loss:
  realism:
    train:
      rec: 10.
      cycle: 2.
      lpips: 0.
      cx: 0.
    val:
      rec: 10.
      cycle: 1.
      lpips: 1.
      cx: 1.
  triplet:  # only works when 'triplet' in train_dataset
    rec: 10.
    rec_code: '0,0,0,0,1,1'
    cycle: 0.
    lpips: 0.
    cx: 0.
  sid:
    id: 5.
    att: 10.
    mouth: 0.5
mouth_net:
  use: true
  feature_dim: 128
  crop_param:  # (w1, h1, w2, h2) of PIL.Image
    - 28
    - 56
    - 84
    - 112
  weight_path: "../../modules/third_party/arcface/weights/mouth_net_28_56_84_112.pth"
model:
  in_size: 512